models:
  all:
    Private:
      stablelm-alpha: StableLM (Alpha)
      gpt4all: GPT4All
      azure-openai: Azure OpenAI (GPT-3.5-Turbo)
    Public:
      openai: OpenAI (GPT-3.5-Turbo)
  selected: openai
sources:
  all:
    Cloud:
      abs: Azure Blob Storage
      gcs: GCP Cloud Storage
      s3: Amazon S3
    Desktop:
      dropbox: Dropbox
      gdrive: Google Drive
      onedrive: OneDrive
    SaaS:
      notion: Notion
      blackboard: Blackboard
      confluence: Confluence
      git: Git
  selected:
  - s3
tools:
  all:
    google: Google
    math: Calculator
    wikipedia: Wikipedia
  enabled: true
  selected:
  - google
  - math
  - wikipedia
access:
  credentials:
    usernames:
      admin:
        email: admin@acme.com
        name: Admin Person
        password: $2b$12$4ps73LGylcwHRUty9eV84uCULxqr7V1/ZNUQ53/h1Zv573CvEmiXS
  cookie:
    expiry_days: 30
    key: docq_access_cookie
    name: docq_access_cookie